### ISSUE TITLE
Fixed Login Issue

### ISSUE THREAD

**Issue by harrytwright** [garrincha33/One-Post#2]
`
You Missed a '}' after the let user = user
            
            if error == nil {
                
                print("Rich: EMAIL USER AUTHENTICATED\(error.debugDescription)")
                
                if let user = user {
                    
                    let userData = ["provider" : user.providerID]
                    self.completeSignIn(id: user.uid, userData: userData)
                }
                
            } else {
`

**Comment by harrytwright** [comment]
The whole code if you have issues with sorting the brackets out

``` MARKDOWN
@IBAction func loginBtn(_ sender: AnyObject) {

        guard let email = usernameLoginTxtField.text, !email.isEmpty else {

            print("The email field needs to be populated")
            return
        }

        guard let pwd = passwwordLoginTxtField.text, !pwd.isEmpty else {
            print("The password field needs to be populated")
            return
        }

        FIRAuth.auth()?.signIn(withEmail: email, password: pwd, completion: { (user, error) in

            if error == nil {

                print("Rich: EMAIL USER AUTHENTICATED\(error.debugDescription)")

                if let user = user {

                    let userData = ["provider" : user.providerID]
                    self.completeSignIn(id: user.uid, userData: userData)
                }

            } else {

                print("did we get here")

                FIRAuth.auth()?.createUser(withEmail: email, password: pwd, completion: { (user, error) in

                    if error != nil {

                        print("Rich: unable to authenticate with firebase \(error.debugDescription)")

                    } else {

                        print("RICH: successfully authenticated and added user to firebase....")

                        if let user = user {

                            let userData = ["provider" : user.providerID]
                            self.completeSignIn(id: user.uid, userData: userData)

                        }
                    }

                })

            }

        })

    }
```

**Comment by garrincha33** [comment]
omg are you serious?

im so sorry mate thanks for your help how embarrassing 

just goes to show what a fresh pair of eyes can do :-)

**Comment by harrytwright** [comment]
It's okay mate, we all do it haha!

Also, if you wanted rather than using a view to fit under your text field you could use this, https://github.com/Skyscanner/SkyFloatingLabelTextField it is a class for textfields to make them pop and stand out all in interface builder.

Good look with the rest of the app pal!

**Comment by garrincha33** [comment]
haha cheers fella, oh wow I like this a lot definitely checking this out.

thanks its going ok got some good ideas that hopefully I can implement

cheers again for your help :-)

**Comment by harrytwright** [comment]
No Problem pal!
